name: Build Gradle project

on:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: chmod +x ./gradlew && ./gradlew build
